
include: package:pedantic_mono/analysis_options.yaml
linter:
  rules:
    avoid_classes_with_only_static_members: false
    cascade_invocations: false
    comment_references: false
    constant_identifier_names: true
    library_private_types_in_public_api: false
    one_member_abstracts: false
    always_use_package_imports: true
    use_build_context_synchronously: false
    use_setters_to_change_properties: false
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  plugins:
    - custom_lint

  errors:
    duplicate_ignore: ignore
    invalid_annotation_target: ignore
    invalid_use_of_visible_for_testing_member: error
    todo: ignore
    missing_required_param: warning
    missing_return: warning

custom_lint:
  rules:
    - missing_provider_scope: false