targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          checked: true
        generate_for:
          include:
            - lib/features/**/*.dart
      freezed:
        generate_for:
          include:
            - lib/features/**/*.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/**/*.dart