name: hanabito
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: ^9.2.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  gap: ^3.0.1
  go_router: ^14.3.0
  pedantic_mono: ^1.28.0
  riverpod_annotation: ^2.3.5
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  roggle: ^0.4.2+1


dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  fonts:
    - family: Sawarabi_Gothic
      fonts:
        - asset: assets/font/Sawarabi_Gothic/SawarabiGothic-Regular.ttf
          weight: 400

  assets:
    - assets/image/
    - assets/icon/